modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="cowpewter_woc"
version="1.0.0"
displayName="World of Color"
credits="Made with love thanks to mod maker MCreator - https://mcreator.net/about"
displayURL="https://cowpewter.com"
authors="cowpewter, MCreator"
description='''
Adds color variations to lots of blocks, via a new set of dyes.
'''

[[dependencies.cowpewter_woc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




